CREATE TABLE ROLES (
ID BIGINT PRIMARY KEY AUTO_INCREMENT,
ROLE_NAME VARCHAR(15) NOT NULL,
);

CREATE TEBLE USER_TO_ROLE (
  ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  FK_USER_ID BIGINT NOT NULL,
  FK_ROLE_ID BIGINT NOT NULL
      CONSTRAINT FK_UTR_USERS FOREIGN KEY  (FK_USER_ID)
      REFERENCES ROLES(ID)

      CONSTRAINT FK_UTR_ROLES FOREIGN KEY  (FK_ROLE_ID)
      REFERENCES ROLES(ID)
)