CREATE TABLE ROLES (
ID BIGINT PRIMARY KEY AUTO_INCREMENT,
ROLE_NAME VARCHAR(15) NOT NULL,
);


CREATE TABLE USER_TO_ROLE (
  ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  FK_USER_ID BIGINT NOT NULL,
  FK_ROLE_ID BIGINT NOT NULL,
    CONSTRAINT FK_UTR_TO_USERS FOREIGN KEY (FK_USER_ID)
            REFERENCES USERS(ID),
    CONSTRAINT FK_UTR_TO_ROLES FOREIGN KEY (FK_ROLE_ID)
            REFERENCES ROLES(ID)
);